# Generated by Django 4.2.14 on 2024-08-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_index', models.IntegerField(default=-1)),
                ('task_data', models.JSONField(default=list)),
            ],
        ),
    ]
